version: '3.8'

services:
  frontend:
    container_name: internship_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
